id: P004622
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-17 11:44:56.343514
source_metadata:
  id: bdr:W3CZ1323
  title: ཀུན་དགའ་བཟང་པོའི་རྣམ་ཐར།
  author: ''
  volumes:
    bdf47d812fad4abd80709e33df5722dd:
      image_group_id: I1KG9682
      title: ''
      volume_number: 1
      total_pages: 134
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
